database:
  default:
    type: "mysql"
    host: "mysql"
    port: "3306"
    user: "cool"
    pass: "__MYSQL_APP_PASSWORD__"
    name: "cool"
    charset: "utf8mb4"
    timezone: "Asia/Shanghai"
    createdAt: "createTime"
    updatedAt: "updateTime"

redis:
  cool:
    address: "redis:6379"
    db: 0

cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8300"

modules:
  base:
    jwt:
      sso: false
      secret: "__JWT_SECRET__"
      token:
        expire: 7200
        refreshExpire: 1296000
    middleware:
      authority:
        enable: 1
      log:
        enable: 1
